### ISSUE TITLE
Roller Shutters: automatic STOP command before setting new position

### ISSUE THREAD

**Issue by rebzone** [mvalla/openhab2-addons#10]
Given a position (%) or command (UP/DOWN), send an automatic STOP command when a new position is set or command is given.

Example steps:
** Roller shutter state = 100
1) User set 50% position
2) Binding sends UP command to 50%
3) User set 20% position before the 50% is reached
4) Binding sends STOP command
5) Binding sends UP command to 20%

This enhanchement could also bypass actuators timing issues.

**Comment by mvalla** [comment]
fixed in beta8
