### ISSUE TITLE
Feature Install Error esh-io-transport-upnp

### ISSUE THREAD

**Issue by MaxBec** [mvalla/openhab2-addons#100]
Hello everyone,

i followed the readme.md for a fresh install of an openhabian system with the openwebnet binding. At the step:

```
feature:install openhab-transport-serial
feature:install esh-io-transport-upnp

```

the installation is failing and i get the following message:
`Error executing command: No matching features for esh-io-transport-upnp/0`

**Comment by mvalla** [comment]
Which version of OH2 are you using?

**Comment by mvalla** [comment]
for openHAB 2.5.x the dependencies to be activated are:

- `feature:install openhab-transport-serial`
- `feature:install openhab-core-io-transport-upnp`

I updated the instructions in the README
