### ISSUE TITLE
Update to 2.5 issue

### ISSUE THREAD

**Issue by vaaduz** [mvalla/openhab2-addons#103]
Hello to all,
after the update to Openhab 2.5 it doesn't work. I need to do something?

Thx

**Comment by mvalla** [comment]
You should provide more info here: what does not work, exactly? Did you follow the installation instructions carefully in particular activation of dependencies?
There are other users that are using the binding successfully on OH 2.5, so I would not expect any big issue with the new release.

**Comment by vaaduz** [comment]
Hi Valla thanks for your answer.
My actual situation is: In Papaer UI  I can see all "Things" and the Web Server in state: UNINITIALIZED.
Regarding the installation, before the update everything worked correctly...

**Comment by mvalla** [comment]
Does the binding appear in the list of bindings in PaperUI? 
In the README Instructions it is said that dependencies must be re-activated after each OH upgrade. Did you do that?

**Comment by vaaduz** [comment]
mvalla, I solved!
I forgot to re-activate the dependencies.
Thank you very much for your support :-)

**Comment by mvalla** [comment]
Then I will close this. Next time before opening an issue on GitHub, go and look for help on the openHAB community forum
