### ISSUE TITLE
[Thermo feature]: add support for heating valves

### ISSUE THREAD

**Issue by m4rky-m4rk** [mvalla/openhab2-addons#108]
This feature was available for OH2 but not currently supported in OH3. It works at start up but the valve items are not updated after start up.

It is useful to create a heat map chart to track the whole house heating demand zone by zone

![image](https://user-images.githubusercontent.com/26285654/148777310-f0bd39ac-ccd6-4385-aa06-13fcfecbf803.png)

**Comment by mvalla** [comment]
@m4rky-m4rk please move this issue/feature to openhab/openhab-addons repository

**Comment by m4rky-m4rk** [comment]
Done
https://github.com/openhab/openhab-addons/issues/12019

**Comment by mvalla** [comment]
closing this as it has been moved to openhab/openhab-addons repository
