### ISSUE TITLE
setmode "auto" must not allow to adjust temperature

### ISSUE THREAD

**Issue by weltraumbagger** [mvalla/openhab2-addons#23]
if setmode is "protection" then the target-temp will be set to the in 3550 tithermo heating central pre-defined value.
the same has to be for setmode "auto". the pre-defined value should be set.
would be great if possible to avoid manual changing temperatures in this modes. if not, i think it can be realized in sitemap (make item setpoint invisible in this modes)

**Comment by mvalla** [comment]
can you do this test:
- set a thermostat to Manual with set temperature 18°
- using the [official OpenWebNet Client from BTicino](https://www.myopen-legrandgroup.com/content/uploads/2016/06/OpenWebNet_Client_windows_32bit.zip ) -> tab TOOLS (for Windows) 
- connect to your BTicino GW and click "open event"
- goto 3550 and set the same thermostat to AUTO so that temperature is set to the pre-defined value
- copy-paste here the client log window (make sure all log is shown, use more images i needed)

**Comment by weltraumbagger** [comment]
hi massimo,

please check if ok. i set to manual, 18 deg. then on 3550 set mode to auto, temp then switched to 21.5 deg. see pics:

![1](https://user-images.githubusercontent.com/41570278/51369572-61671a00-1af4-11e9-9708-dcc1ae557748.JPG)
![2](https://user-images.githubusercontent.com/41570278/51369573-61ffb080-1af4-11e9-8de5-e9a5fa52908e.JPG)
![3](https://user-images.githubusercontent.com/41570278/51369574-61ffb080-1af4-11e9-9394-9fc79ba25d99.JPG)
![4](https://user-images.githubusercontent.com/41570278/51369575-61ffb080-1af4-11e9-8e0d-ebe503c036a2.JPG)


best, stefan

**Comment by mvalla** [comment]
What is the WHERE of the thermostat you set to manual/18degree ?

**Comment by weltraumbagger** [comment]
it is "17"

**Comment by mvalla** [comment]
from the log, figure 2, it looks like you are setting Central Unit 3550 back to PROGRAM 01:
`*4*1101*#0#`
and then target temp of Thermostat_17 is automatically set to 20.5°:
*#4*17*12*0205*3##    (WHERE=17, 0205 is 20.5°)
The last message is used by the binding to update the targetTemperature channel value.
Isn't this the pre-defined value you are expecting?

**Comment by weltraumbagger** [comment]
oh sorry, your right! 
i don´t like the 3550 because complicated to manage.
again from the beginning:

here i changed on a touchscreen 4890 from auto to manual 18 degrees (zone 17):
![1a](https://user-images.githubusercontent.com/41570278/51415951-e6dfde00-1b77-11e9-8d0c-c8db8f816219.JPG)
![1b](https://user-images.githubusercontent.com/41570278/51415957-ec3d2880-1b77-11e9-8b11-f7160f1ddac1.JPG)

and here i changed on the same touchscreen (4890) back form manual to auto (20.5 deg):
![2a](https://user-images.githubusercontent.com/41570278/51415986-05de7000-1b78-11e9-8c89-2046dfdfd187.JPG)
![2b](https://user-images.githubusercontent.com/41570278/51415989-08d96080-1b78-11e9-81ca-b68c2e3baaa3.JPG)
![2c](https://user-images.githubusercontent.com/41570278/51415992-0bd45100-1b78-11e9-9277-ba7ed7b6b135.JPG)

and here i changed on the 3550 from auto to manual 18 deg (again zone 17):
![3a](https://user-images.githubusercontent.com/41570278/51416440-d3357700-1b79-11e9-9ea6-b0916a40b9a3.JPG)

and at least i changed on the 3550 back from manual to auto (20.5 deg):
![4a](https://user-images.githubusercontent.com/41570278/51416461-e7797400-1b79-11e9-8cdd-d97070502edc.JPG)
![4b](https://user-images.githubusercontent.com/41570278/51416466-eb0cfb00-1b79-11e9-82c3-1f2c0a2d4e75.JPG)
![4c](https://user-images.githubusercontent.com/41570278/51416468-ee07eb80-1b79-11e9-8c8b-fbf36adfcb50.JPG)

**Comment by weltraumbagger** [comment]
this issue seems to be solved because now if i change the temperature the mode switches to manual - perfect!

**Comment by mvalla** [comment]
reported as solved by beta9-2
