### ISSUE TITLE
automatic discovery of bus gateway 

### ISSUE THREAD

**Issue by mvalla** [mvalla/openhab2-addons#28]
a bus gateway on the same network should be discovered automatically and put in Inbox.
UPnP could be used.
(password will still be needed to be configured in the Thing properties)

**Comment by giusfac** [comment]
Hi
I have a MyHOMEServer1
But i can't able to find it even in manual mode
Ping to the address works
How can i fix it?

thanks
Giuseppe

**Comment by Jeby057** [comment]
Hi,

I have a MyHOMEServer1 too and it works.

- Have you check the log file with DEBUG mode ? (/openhab/userdata/logs/openhab.log)
- Have you install Eclipse IoT Market add-on?
- Have you set correctly the IP address ? 
- If you have a firewall, have you open the port 20000?
- Have you set correctly the password ? If you don't have it, you can change it with MyHomeUp application (Technical user -> Properties -> System -> Password OPEN)

With the hope that this can help you !

**Comment by mvalla** [comment]
> Hi
> I have a MyHOMEServer1
> But i can't able to find it even in manual mode
> Ping to the address works
> How can i fix it?
> 
> thanks
> Giuseppe

You should ask for assistance on the main thread: 
https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/360
there you should describe your configuration (IP address of MyHOMEServer1, version of openHAB, where it is deployed, version of the OpenWebNet binding installed) , and attach some log lines: copy past the logs just after you try to configure the gateway manually from PaperUI.
Even before that you also have to check the README and follow all its installation instructions.

**Comment by mvalla** [comment]
added in version 2.5.0-M1
