### ISSUE TITLE
Problem reconnecting gateway after first cleanup

### ISSUE THREAD

**Issue by umbz** [mvalla/openhab2-addons#31]
i attempt to install bindings first time:

all ak , i added gateway manually and then my things are recognized via automatic scan..

now i clean up all bticino bindings , and started from beginning ...

when i try to reconnect bticino gateway the connection fail  with status OFFLINE - COMMUNICATION_ERROR 

this is may log.. any idea? i have beta7

``2018-12-05 01:34:11.973 [ERROR] [org.openwebnet.AbstractOpenGateway  ] - ERROR IN Java $MODULE$: connection cannot be established
2018-12-05 01:34:32.135 [INFO ] [bnet.handler.OpenWebNetBridgeHandler] - ==OWN== BridgeHandler status still UNKNOWN. Setting device=openwebnet:bus_gateway:c7d5e077 to OFFLINE
2018-12-05 01:43:59.238 [INFO ] [ery.OpenWebNetBridgeDiscoveryService] - ==OWN:BridgeDiscovery== ------ startScan() - SEARCHING for bridges...
2018-12-05 01:43:59.333 [INFO ] [ery.OpenWebNetBridgeDiscoveryService] - ==OWN:BridgeDiscovery== no serial ports found
2018-12-05 01:44:28.282 [ERROR] [org.openwebnet.AbstractOpenGateway  ] - ERROR IN Java $MODULE$: connection cannot be established
2018-12-05 01:44:48.334 [INFO ] [bnet.handler.OpenWebNetBridgeHandler] - ==OWN== BridgeHandler status still UNKNOWN. Setting device=openwebnet:bus_gateway:d9268d16 to OFFLINE
 ==OWN:BridgeDiscovery== ----

**Comment by Gozilla01** [comment]
@umbz 
Take a test with the latest version
[https://community.openhab.org/t/bticino-openwebnet-adding-cen-commands-design/54142/24](url)

**Comment by umbz** [comment]
Faccio prima a scrivere in italiano ... sono un po' di fretta.
disisntallata la beta7 l'area bindings mi propone l'ultima... perfetto installo installazione ok ma nella inbox nulla... 
Scopro nel log questo: 

Installed bundle, but failed to start it: Could not resolve module: org.openhab.binding.openwebnet [217]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.osgi.service.component.annotations; resolution:="optional"
  Unresolved requirement: Import-Package: gnu.io

**Comment by Gozilla01** [comment]
Ciao @umbz 
io ho installato rasberry org.openhab.binding.openwebnet-2.4.0-b9-pre2.jar e funzionanti:
- 2.4.0M7 su Rasberry
- 2.3.0 su Nas

Il file .jar nel direttorio openhab2-addons, elimino il vecchio e copio il nuovo è funziona

Prova a ridare i comandi dalla console Karaf 
feature:install openhab-transport-serial
feature:install esh-io-transport-upnp ( questa se hai la versione 2.4.0)

**Comment by mvalla** [comment]
the binding is under development: you have always to use the latest version and, most importantly, !!READ!! the README for installation instructions.
For help on installation and configuration, use the community forum (in English) and not GitHub.
 I will close and delete this issue in a couple of days.

**Comment by umbz** [comment]
hi, mvalla, my plugin was installed correctly! but i deleted old previous discovered bindings , then the plugin was "broken" .. it is not properly an installation problem!

**Comment by umbz** [comment]
ok for some reasons after binfings cleanup , there will do: feature:install openhab-transport-serial

now is working.
