### ISSUE TITLE
Alarm by aux command..

### ISSUE THREAD

**Issue by umbz** [mvalla/openhab2-addons#32]
hi mvalla again , 
will it be in the roadmap controlling burglar alarm (34686) by aux commands ?

**Comment by umbz** [comment]
#12

**Comment by umbz** [comment]
https://www.domoticz.com/forum/viewtopic.php?t=14053&start=40

**Comment by mvalla** [comment]
I think this is a duplicate of #12, correct?
If yes, I will close this as duplicate.

**Comment by Gozilla01** [comment]
I suppose it's the same thing, but I have no Bticino alarm

**Comment by Gozilla01** [comment]
See pull request [58](https://github.com/mvalla/openhab2-addons/pull/58)

**Comment by Gozilla01** [comment]
Remove label question

**Comment by mvalla** [comment]
Close this as duplicate of #12
