### ISSUE TITLE
Command Switch CEN/CEN+ to bus

### ISSUE THREAD

**Issue by Gozilla01** [mvalla/openhab2-addons#33]
Add the ability to control CEN / CEN + via Switch.
This allows sending the command on Bus.
In my case it would enable the scenario on MH202 from OpenHab (Web and Iphone)
es.
`Switch 	CEN_Tap_Giorno "GEN Giorno" <rollershutter>	(C_Corridoio, G_Cen)  [ "Lighting" ]				{ channel="openwebnet:bus_scenario_control:mybridge:cen_gen_giorno:button2:PRESSED_EXT", expire="2s,command=OFF" }`

This implementation could be integrated with this request #22

**Comment by mvalla** [comment]
Thanks @Gozilla01 this must be surely added to complete CEN/CEN+ support.
Is the example something you have tested from PaperUI ?
I am not sure about the last part of the channel: PRESSED_EXT, can this be added to a channel definition for an Item?

The thing that is not clear to me yet is how to re-create two buttons one for SHORT_PRESSURE and one for LONG_PRESSURE to be used as items in the PaperUI, ClassiUI and mobile apps
Any suggestion is welcome!

**Comment by mvalla** [comment]
closed in release beta9-1
