### ISSUE TITLE
Support for WHO=4, WHAT=21,22,23 

### ISSUE THREAD

**Issue by Gozilla01** [mvalla/openhab2-addons#36]
Implement the commands: WHAT = 21,22,23 [link](https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/376)
You see:

> Can we choose 1,2,3, summer, winter programs on the 3550 plant?
Currently “active mode” displays only the state “Off and anti freeze” not the state “auto or manual”
2018-12-28 09: 55: 36.786 [WARN] [penwebnet.message.openMessageFactory] - ## openwebnet ## unsupported WHAT 1101 from frame * 4 * 1101 * # 0 ##
2018-12-28 09: 55: 36.830 [WARN] [penwebnet.message.OpenMessageFactory] - ## openwebnet ## unsupported WHAT 21 from frame * 4 * 21 * # 0 ##
2018-12-28 09: 55: 39.937 [WARN] [penwebnet.message.openMessageFactory] - ## openwebnet ## unsupported WHAT 22 from frame * 4 * 22 * # 0 ##
2018-12-28 09: 55: 36.860 [WARN] [penwebnet.message.OpenMessageFactory] - ## openwebnet ## unsupported WHAT 23 from frame * 4 * 23 * # 0 ##

**Comment by mvalla** [comment]
for WHO=4, these commands are:
21 Remote control enabled
22 At least one probe OFF
23 At least one probe in Anti Freeze
which seem not so useful. What is the use-case?

**Comment by Gozilla01** [comment]
@tagada
you can answer Massimo?

**Comment by weltraumbagger** [comment]
sorry i don´t understand, the who=4 commands that massimo described i cannot imagine what they are usefull for.
michese asked for the possibillity to switch between the 3 summer and 3 winter programms, that may be usefull for somebody. 
for example i use winterprogramm1 for normally, winterprogramm2 when in holiday, well thats nearly never :)

**Comment by mvalla** [comment]
since there was no positive feedback, these commands will not be implemented for the moment. This issue will be closed soon.

**Comment by mvalla** [comment]
closed as the is no clear use case associated to this support request

**Comment by rinal13** [comment]
Hello mvalla,
I was contributing for the heating control at the bticino binding v1 and I Implemented there these codes.
But important for these codes is that these are not commands,
these are status messages from the central temperature control. Which are for information quite useful.
i.e 21 Remote control enabled means that the central temperature controller can be controlled remotely i.e. by some Touch screens or by the binding.
