### ISSUE TITLE
Energy Meter polling (WHO=18)

### ISSUE THREAD

**Issue by gabrieledaltoe** [mvalla/openhab2-addons#39]
Need to pooling Energy Data from BUS.
BUS respond to pooling.. there is no events when power changes
https://community.openhab.org/t/f520-energy-managemet/61746/16

**Comment by mvalla** [comment]
Energy update events should be requested by the binding for each energy thing:
`*#18*<where>*#1200#<type>*<time>##`.
(for <time>= 1 receive update events every 1 min).

Must be tested with both  F520 and F521

See: https://community.openhab.org/t/f520-energy-managemet/61746/

**Comment by mvalla** [comment]
added 1min update events registration in version 2.5.0-M1
