### ISSUE TITLE
support for Bticino movement sensors

### ISSUE THREAD

**Issue by Rob-VF** [mvalla/openhab2-addons#4]
Hello Massimo, all

please find following the items not supported.

By the log I read:

`2018-05-30 08:30:46.697 [INFO ] [et.handler.OpenWebNetLightingHandler] - ==OWN:LightingHandler== updateLightOnOffState() Ignoring unsupported WHAT for thing openwebnet:bus_on_off_switch:4005f1b5:88h4h03. Frame=<*1*34*88#4#03##>`
`2018-05-30 08:31:17.457 [INFO ] [et.handler.OpenWebNetLightingHandler] - ==OWN:LightingHandler== updateLightOnOffState() Ignoring unsupported WHAT for thing openwebnet:bus_on_off_switch:4005f1b5:88h4h03. Frame=<*1*39*88#4#03##>`

Those frames are generate by a AM5658 Green Switch, it sends `34` when triggered ON, it sends `39` when OFF (ON timer expiration)

In the same device family: http://www.catalog.bticino.com/myhomegb/files/assets/basic-html/page-637.html

The implementation of those devices could be useful in case you want to create a "logic" to stop the daytime ON of the lights or if you want to use the movement information to trigger some other logic (i.e. time of the day, movement > open shutters)

**Comment by mvalla** [comment]
it will be added to the next 2.5.0-M1 version. The thing will be bus_switch. To distinguish it from a normal switch, i ask you to:


1. Download this official client from BTicino: 
https://www.myopen-legrandgroup.com/developers/  >> tab TOOLS >> download and run **OpenWebNet Client - Windows** (exec file is `OpenWebNet_Client.exe`).
1. put the IP address of your BTicino gateway and its password (select HMAC if password has characters and not just numbers)
1. write `*#1*88#4#03##` in the Frame box, click `Send`
1. the copy here a picture of the result

**Comment by Rob-VF** [comment]
Hello Massimo,

please find following the messages:

*1*0*88#4#03##===*#1*88#4#03##===
and
*#*1##===*#1*88#4#03##===

Thanks

**Comment by mvalla** [comment]
great! can you put the answer using code fences ? the `*` and `#` make the messages difficult to read

**Comment by Rob-VF** [comment]
> great! can you put the answer using code fences ? the `*` and `#` make the messages difficult to read

Done :)
