### ISSUE TITLE
group commands [WHERE=#n ?]

### ISSUE THREAD

**Issue by k0nti** [mvalla/openhab2-addons#40]
Group Command s like bticino groups lights or roller shutter are not integrated yet

In my Log tail it looks light that
“2018-12-27 23:12:40.420 [DEBUG] [bnet.handler.OpenWebNetBridgeHandler] - ==OWN== ownId=0 has NO THING associated, ignoring it”

bg Patrick

Community Openhab k0nti

**Comment by k0nti** [comment]
is already existing. sorry

**Comment by mvalla** [comment]
duplicate of #35
