### ISSUE TITLE
Rollershutter management through Google Assistant Open/Close commands

### ISSUE THREAD

**Issue by enrico-cc** [mvalla/openhab2-addons#41]
Nice to have request:

When giving to Google Assistant an open or close command for the roller-shutters the following error is logged:
`2019-01-06 23:38:41.554 [WARN ] [rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/TapparellaSinistraCameraMatrimoniale' with an invalid status value 'OFF'.`

It would be nice to translate and "OFF" request with a "UP" command to the bus and a "ON" request with a "DOWN" command

**Comment by mvalla** [comment]
This is not possible, as the error is not returned by the OpenWebNet binding but by the OH2 REST API which is invoked by Google Assistant.
This is more an issue for Google Assistant integration in openHAB2, and of Google Assistant itself: at the moment it [does not support blinds/shutter device types](https://stackoverflow.com/questions/51353342/google-smart-home-command-for-blinds)

**Comment by enrico-cc** [comment]
Thanks anyway for checking!
