### ISSUE TITLE
Duplicate devices when connecting to Google Home

### ISSUE THREAD

**Issue by theov3rc0mer** [mvalla/openhab2-addons#44]
When syncing devices with Google Home everything is ok and the items marked with the correct tags appear to work fine. The problem is that I am also getting lots of duplicate devices (they appear to be duplicates of the ones I added at my rooms), which are marked with the generic name "Temperature" or "Switch". They show up under the section "In your home".

**Comment by mvalla** [comment]
How did you create the things/items to be visible for Google Home ? 
Via PaperUI (auto-discovery or manually) or via things/items config files?

**Comment by theov3rc0mer** [comment]
Things were discovered via PaperUI and auto-discovery, items are defined manually in the .items file according to the example in the guide.

**Comment by mvalla** [comment]
These duplicate devices should come from items created automatically by PaperUI.
You can check which items you have in OH2 using:
- http://<openHAB_IP>:8080/rest/items

All items here that have the correct tags, will be also exported to assistants like GH.
Check your setting for *Simple Mode item linking* (`PaperUI > Configuration > System > Item Linking`)
If you have SimpleMode=ON, then items have been created both when you added the Things via PaperUI and also using your .items file.
(by setting SimpleMode=OFF you can go to the new Items menu and see all the Items also from there).

If you confirm, this is not an issue with the binding.

**Comment by theov3rc0mer** [comment]
Ok it's exactly as you described. Sorry I am new to the openHab software.

**Comment by mvalla** [comment]
this is not an issue with the binding, but a duplicate item configuration
