### ISSUE TITLE
error installing requested feature

### ISSUE THREAD

**Issue by modenet** [mvalla/openhab2-addons#50]
I upgraded openhab2.4 from 2.3; after openwebnet2 disappeared.
I folowed instruction and launched: 
feature:install openhab-transport-serial
feature:install esh-io-transport-upnp
but both terminated with same error:
 Error executing command: Unable to build resource for https://drive.google.com/uc?export=download&id=1MWIIoyLne_JNALZFg0TcE1GoTTShDO3f: Unsupported 'Bundle-ManifestVersion' value: 1

**Comment by mvalla** [comment]
This does not seems to be an error related to the OpenWebNet binding itself. The two commands are managed by Karaf concole and openHAB core bundles, so they should give no error if the 2.4 installation is correct.  I suggest to start a new 2.4 installation from scratch.

**Comment by modenet** [comment]
thanks, I was seeking for suggests
