### ISSUE TITLE
add support for MH201 gateway

### ISSUE THREAD

**Issue by efa** [mvalla/openhab2-addons#86]
## Your Environment

Ubuntu 18.04 and Raspbian Jessie

MH201 seems the cheaper gateway:
http://www.homesystems-legrandgroup.com/BtHomeSystems/productDetail.action?productId=053
It is also an hotel scenario manager (up to 50 scenarios for 100 rooms) and light status memory.
For light, automation and device configuration is supported by MyHome_suite software:
http://www.homesystems-legrandgroup.com/BtHomeSystems/home.action
for hotels related functions is supported by MyHotel_suite software:
http://www.homesystems-legrandgroup.com/BtHomeSystems/productDetail.action?productId=066

**Comment by mvalla** [comment]
can you provide DEBUG log lines when the device is discovered?
1. set log level to DEBUG (see here info)
1. delete your MH201 thing (from PaperUI or text file) (you can put it back after the test)
1. start a new device discovery and look into the openHAB log (http://<your_OH_ip>:9001)

**Comment by mvalla** [comment]
fixed in [own-2.5.0.M3](https://github.com/mvalla/openhab2-addons/releases/tag/own-2.5.0.M3)

**Comment by efa** [comment]
hi, this fix was integrated in upstream Milestone 2.5.0.M4 ?

**Comment by efa** [comment]
I saw: Bticino Binding binding-bticino1 - 1.14.0.M4

**Comment by mvalla** [comment]
This issue is closed. Version 2.5.0.M3 of the binding (published both here in Releases and on marketplace) solves the issue

**Comment by efa** [comment]
sorry, it is not clear to me, if I install OpenHAB Milestone 2.5.0.M4 plus its plugins I've got this fix, or I had to install this plug-in in another way?

**Comment by mvalla** [comment]
openhab releases do not include yet this openwebnet binding, they only include the bticino v1 binding which is much older than this one, so you have to install the openwebnet binding separately.
You should read very carefully the [README.md](https://github.com/mvalla/openhab2-addons/blob/openwebnet-dev/bundles/org.openhab.binding.openwebnet/README.md) and [README_beta.md](https://github.com/mvalla/openhab2-addons/blob/openwebnet-dev/bundles/org.openhab.binding.openwebnet/README_beta.md) files first.

Also this is not a discussion/support forum. Should you have any questions refer to the [main thread](https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377) in the OH2 community.
