### ISSUE TITLE
Support for contacts interfaces (WHO=25)

### ISSUE THREAD

**Issue by m4rky-m4rk** [mvalla/openhab2-addons#9]
https://www.myopen-legrandgroup.com/content/uploads/2016/06/WHO_25.pdf

Hi,
It would be great if there was support for basic contacts interfaces F428 and 3477.

I use these to check the state of traditional switches and sensor relays eg weather station sensor limit relays.

As far as I know the only way to visualise contact status is either using an LCD panel eg Screen10  or using a scenario and a dummy actuator to act as indicator of the contact state.

It would be great if these were supported in Openhab and then there would be another way to visual their states, create rules etc.

Thanks , Mark

**Comment by mvalla** [comment]
closed in release beta9-1
